feat: improve navbar and footer
Los-creativos/cloteck-e pull request #18
Opened 2023-11-16 23:40 UTC by isaias-rojas

2023-11-21 20:02 UTC, AndrePzDn requested changes
Pls don't forget to put endlines to the files

2023-11-21 20:02 UTC, AndrePzDn commented on app/components/home/ProductLIst.tsx
> +    return <div>Error fetching products: {error}</div>;
This display should be at middle of the div ![IMG_20231121_155837.jpg](https://github.com/Los-creativos/cloteck-e/assets/90226510/080c948e-2895-4c99-a8a4-e01ccca7e68e)

2023-11-22 12:48 UTC, AndrePzDn approved these changes

2023-11-22 12:52 UTC, gabitrujillo approved these changes

2023-11-22 12:53 UTC, merged